/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sschr15_NativeBackedIntArray */

#ifndef _Included_com_sschr15_NativeBackedIntArray
#define _Included_com_sschr15_NativeBackedIntArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    createNativeArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_sschr15_NativeBackedIntArray_createNativeArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    createFromArray
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_com_sschr15_NativeBackedIntArray_createFromArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sschr15_NativeBackedIntArray_equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    get
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_sschr15_NativeBackedIntArray_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    set
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sschr15_NativeBackedIntArray_set
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sschr15_NativeBackedIntArray_size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sschr15_NativeBackedIntArray_clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    fill
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_sschr15_NativeBackedIntArray_fill
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    sort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sschr15_NativeBackedIntArray_sort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sschr15_NativeBackedIntArray
 * Method:    deleteNativeArray
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sschr15_NativeBackedIntArray_deleteNativeArray
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
